# Spring properties 
spring.application.name=addition-service 
spring.freemarker.enabled=false 
spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/addition-server/templates/ 
error.path: /error 
# HTTP Server 
server.port: 2222 # INPUT_REQUIRED {The port number for the addition service, change if needed} 
eureka.client.serviceUrl.defaultZone=http://localhost:5467/eureka/ 
eureka.client.instance.leaseRenewalIntervalInSeconds=5